id: PC5447014
initial_creation_type: input
source_metadata:
  Title: Arya Amoghpash hrdaya nama Mahayana Sutra
  Editor: Shakya, M. B.
  Publisher: Nagarjuna Institute of Exact Methods
  Place of Publication: Nepal
  Year: '1988'
  Ārya amoghapāśahṛdaya nāma mahāyānasūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:55:53.130982'
last_modified_at: '2022-03-08T15:55:53.130995'
